export const PLANS = [
  {
    id: 'free',
    name: 'Free',
    description: 'Untuk UMKM yang baru mulai memahami legalitas',
    price_monthly: 0,
    price_annual: 0,
    features: [
      'Analisis 1 Profil Bisnis',
      'ComplianceBot (10 chat/hari)',
      'Akses Checklist Legal Dasar',
      'Generate 2 Dokumen/bulan',
      'Akses Community Support',
    ],
    highlight: false,
  },
  {
    id: 'starter',
    name: 'Starter',
    description: 'Ideal untuk startup dan usaha berkembang',
    price_monthly: 99000,
    price_annual: 990000, // 2 bulan gratis
    features: [
      'Analisis 1 Profil Bisnis',
      'ComplianceBot (Unlimited)',
      'Akses Full Checklist Legal',
      'Generate 10 Dokumen/bulan',
      'Email Digest Regulasi Baru',
      'Custom Email Support',
    ],
    highlight: true,
  },
  {
    id: 'growth',
    name: 'Growth',
    description: 'Untuk perusahaan berbadan hukum (PT/CV)',
    price_monthly: 299000,
    price_annual: 2990000,
    features: [
      'Analisis 3 Profil Bisnis',
      'Priority ComplianceBot',
      'Akses Full Checklist Legal',
      'Generate Dokumen Unlimited',
      'Notifikasi Real-time Alert',
      'Review Kontrak AI (3x/bulan)',
      'Kalkulator BPJS & Pesangon',
    ],
    highlight: false,
  },
  {
    id: 'business',
    name: 'Business',
    description: 'Bagi konsultan atau perusahaan multinasional',
    price_monthly: 799000,
    price_annual: 7990000,
    features: [
      'Analisis 10 Profil Bisnis',
      'Priority ComplianceBot',
      'Akses Full Checklist Legal',
      'Generate Dokumen Unlimited',
      'Custom Alert Dashboard',
      'Review Kontrak AI (20x/bulan)',
      'Kalkulator BPJS Full Akses',
      'Dedicated Customer Success',
    ],
    highlight: false,
  },
];
